spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_system
    username: root
    password: 20020522
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
